const base_de_datos = {
  config: {
    hero_img: 'https://github.com/LeanLabMAR/ProcessController/blob/main/Mayo/GMT_PPT_Template_Global%20TP%20_May_2025.jpg?raw=true', kpi_red_horas: '1.27M Horas', kpi_red_euros: '€ 10\'318.977', kpi_adi_horas: '1.57M Horas', kpi_adi_euros: '€ 12\'494.890', kpi_imp_col: '97.94',kpi_imp_col_sub: '97.94% Clientes implementados COL',kpi_imp_per_sub: '97% Clientes implementados PER',kpi_imp_per: '97',
    txt_red_aplicadas: '• Para los meses de enero a abril de 2026 se presentaron reducciones de tiempo aplicadas por la herramienta On Time, acumulando cerca de €10.31 MM de ahorros para la compañía.', txt_red_estado: '• Se identifica que, durante el periodo de enero a abril de 2026, las horas aprobadas en reducciones se mantienen consistentemente por encima de las denegadas, evidenciando un comportamiento estable en la gestión del proceso.<br><br>​• Así mismo, se observa un incremento en las horas aprobadas de febrero (326.134) frente a enero (300.830), con una ligera variación en abril (320.726), mientras que las horas denegadas presentan una tendencia decreciente a lo largo del periodo, pasando de 200.828 en enero a 177.130 en abril.<br><br>• Este comportamiento refleja una mejora en la aplicación de los criterios de validación y un mayor control sobre las reducciones, lo que contribuye a una gestión más eficiente y alineada con las políticas operativas.​', txt_red_pareto: '• Se identifica que el 54,6% de las horas de reducción justificadas se concentran en las tres principales categorías operativas, evidenciando una alta recurrencia en pocos motivos específicos.<br><br>• Dentro de estas, el motivo más recurrente está asociado a Logged Floor Support (206.592) y Long out of shift interaction (150.673), lo que indica posibles desviaciones entre los tiempos de conexión y la gestión en piso.<br><br>• Recomendación: Se sugiere realizar una revisión y alineación de los horarios programados del equipo de Floor Support en conjunto con Workforce Management, con el objetivo de minimizar estas inconsistencias y reducir la afectación operativa.',
    txt_adi_aplicadas: '• Para los meses de enero a abril de 2026 se presentaron adiciones de tiempo aplicadas por la herramienta On Time, acumulando cerca de €10.84 MM en el periodo.', txt_adi_estado: '• Con respecto al estado de las adiciones entre febrero y abril de 2026, se evidencia un incremento en las horas denegadas, con un pico en marzo y una brecha sostenida frente a las aprobadas.​<br><br>• Este comportamiento sugiere inconsistencias en los criterios de validación, por lo que se hace necesario estandarizar lineamientos y reforzar la comunicación con la operación, especialmente en periodos de alta demanda, para mejorar la eficiencia del proceso​', txt_adi_pareto: '• Se sugiere asignar un limite de horas diarias para las justificaciones de logueo.<br><br>• Se observa que el 51.8% de las horas se concentra en las tres principales categorías, evidenciando una alta focalización en causas asociadas a la gestión operativa.<br><br>• La principal categoría está asociada a “Forgotten login in payroll tool”, la cual representa aproximadamente el 36,0% del total de horas justificadas, reflejando una falta de consistencia en el proceso de logueo a las herramientas de nómina.<br><br>• Adicionalmente, categorías como OPS Training (131.419) y Logged out Floor Support (124.211) complementan el grupo de mayor impacto, reforzando la necesidad de revisar prácticas operativas y de acompañamiento en piso.​<br><br>• En este sentido, se hace necesario profundizar en el análisis de estas tipologías para identificar la causa raíz (conocimiento, habilidad o adherencia), dado el impacto significativo en la gestión y la inversión de tiempo operativo en la justificación de horas. Como siguiente paso, se recomienda estructurar un plan de acción enfocado en mejorar la disciplina operativa y reducir la recurrencia de estas justificaciones.',
    txt_implementacion: '• En Colombia hemos alcanzado un nivel de implementación superior al 97%, mientras que en Perú ya completamos el 100% de las cuentas y las restantes se encuentran actualmente en proceso de implementación.<br><br>• En el caso de Colombia, persisten 2 cuentas pendientes de implementar, las cuales están siendo revisadas con detalle para definir las acciones necesarias que permitan concluir el proceso de forma satisfactoria.', txt_gestion: '• Con respecto a la gestión de On Time durante el periodo de enero a abril de 2026, se evidencia un comportamiento estable con una ligera tendencia al alza en los niveles de cumplimiento. Los resultados mensuales se han mantenido consistentemente por encima del 95%, pasando de 95.36% en enero a 96.25% en abril, lo que refleja un control sostenido en la gestión de los tiempos operativos.​<br><br>• A nivel trimestral, se observa una mejora del Q1 al Q2, incrementando de 96.01% a 96.25%, lo cual confirma la continuidad en las buenas prácticas operativas. Este desempeño está asociado a la gestión oportuna de desviaciones y al seguimiento constante realizado sobre los procesos, permitiendo consolidar niveles altos de adherencia y mantener la estabilidad en los indicadores.',
    txt_inc_area: '• Durante el periodo de enero a abril de 2026, la mayor cantidad de incidencias registradas en la herramienta On Time se concentra en el equipo de Help Desk, con 383 casos que impactaron a 461.589 personas, en su mayoría debido a retrasos en la finalización de la ejecución del Job, posicionándose como el principal foco de afectación operativa.​<br><br>• Adicionalmente, se identifican incidencias asociadas a Master Lilos (76 casos / 56.767 personas) y GBS (17 casos / 86 personas), aunque con un impacto significativamente menor en comparación con Help Desk.​<br><br>• Esta distribución evidencia que las principales afectaciones continúan centralizadas en procesos de soporte y gestión de herramientas, generando impactos relevantes en la disponibilidad y oportunidad de la información, así como en la correcta ejecución de los procesos operativos.​', txt_inc_mes: '• Durante el periodo de enero a abril de 2026 se reporta un total de 476 incidencias en la herramienta On Time. Se observa una disminución significativa de enero (183) a febrero (61), seguida de un incremento progresivo en marzo (87) y abril (145).​<br><br>• Este comportamiento evidencia una variabilidad en la estabilidad operativa a lo largo del periodo, con una mejora inicial que posteriormente se ve impactada por un repunte en las incidencias.<br><br>• Este resultado sugiere la necesidad de reforzar las acciones de seguimiento y control sobre las causas raíz de las incidencias, con el fin de estabilizar la tendencia y asegurar la continuidad en la mejora del desempeño de la herramienta.',
    txt_err_col: '• Durante los meses de enero a abril de 2025 se observa una variación significativa en los errores de nómina, con un incremento marcado entre enero (636 / 0,82%) y febrero (2.333 / 3,05%), seguido de una disminución considerable en marzo (354 / 0,47%) y una leve estabilización en abril (422 / 0,56%).<br><br>• El pico registrado en febrero se concentra principalmente en conceptos sensibles como auxilios legales, bonos, incentivos y ajustes de salario básico, evidenciando fallas en la validación y consolidación de estas novedades dentro del proceso de nómina.<br><br>• Aunque la reducción posterior refleja una mejora en la estabilidad del proceso, el comportamiento del periodo evidencia oportunidades de fortalecimiento en los mecanismos de verificación, control y parametrización de conceptos críticos, con el fin de prevenir recurrencias, evitar afectaciones en los pagos y garantizar la confiabilidad del proceso de nómina.', txt_err_per: '• Durante los meses de enero a abril de 2025 se evidencia un comportamiento variable en los errores de nómina en Perú, con un incremento sostenido desde enero (56 / 0,73%) hasta marzo (176 / 2,47%), seguido de una disminución significativa en abril (44 / 0,62%).​<br><br>• El aumento observado entre febrero (122) y marzo se encuentra principalmente asociado a inconsistencias en la gestión de novedades, particularmente en procesos de Data Calculation y entrenamiento, que impactaron la correcta validación de licencias, vacaciones y otros conceptos sensibles dentro de la nómina.​<br><br>• Aunque la reducción en abril refleja una mejora en la estabilidad del proceso, el comportamiento del periodo pone de manifiesto la necesidad de reforzar los controles en la validación de novedades, así como la articulación entre áreas operativas, con el fin de prevenir recurrencias y asegurar la exactitud y confiabilidad en los pagos de nómina.​', txt_horas_extras: '• A partir de febrero de 2026 se implementó un control exhaustivo por parte del equipo de Payroll Controller para reducir los casos con más de 11.5 horas pagadas. Como resultado, en este mes se evidencia una disminución considerable tanto en la cantidad de casos, que baja a 79, como en las horas pagadas por encima del límite, que se reducen a 124.1 horas.<br><br>• Para abril la tendencia a la baja se mantiene, logrando apenas 30 casos y 39.5 horas. Esta reducción refleja el impacto positivo del seguimiento diario, la depuración de inconsistencias y la validación oportuna de jornadas extendidas, lo que contribuye directamente al control del gasto y a la mejora en la calidad de la información registrada.'
  },
  red_apli: { mes: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo'], man: [324738, 286134, 311631, 308745, 0], auto: [16696, 11864, 8894, 9762, 0], hrs: [341434, 297997, 320525, 318507, 0], cph: ['8.47', '8.47', '8.47', '8.47', '0'], eur: ['2891948', '2524037', '2714849', '2697753', '0'], cop: ['10700209092', '9338937863', '10044941280', '10700209092', '0']},
  red_est: { mes: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo'], app: [297997, 320525, 318507, 321034, 0], den: [200828, 190241, 177130, 190272, 0]},
  red_par: { lbl: ['Logged Floor Support', 'Long out of shift interaction', 'Technical Problem - Client', 'OPS Training', 'Login in client tool loaded incomplete', 'Mandatory logout by TP', 'Logged out Training TP', 'Logged coaching', 'Others'], hrs: [254119, 187077, 102035, 99355, 60135, 38658, 34197, 28978, 196670], pct: [25.4, 44.1, 54.3, 64.2, 70.2, 74, 77.5, 80.4, 100]},
  adi_apli: { mes: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo'], hrs: [410837, 384744, 385859, 396561, 0], cph: ['8.27', '8.27', '8.27', '8.27', '0'], eur: ['3397624', '3181836', '3191058', '3279557', '0'], cop: ['12571210543', '11772793284', '11806912945', '12134360723', '0']},
  adi_est: { mes: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo'], app: [384744, 385859, 396561, 452051, 0], den: [388244, 465155, 449327, 452052, 0]},
  adi_par: { lbl: ['Forgotten login in payroll tool', 'Ops Training', 'Logged out Floor Support', 'Technical Problem - Client', 'Forgotten login in OUT', 'Service Now - Temporary migration IT', 'Technical Problem - Time Keeper', 'Agent in Transfer Process', 'Mandatory logout by TP', 'Client Training - Logged / Logged out', 'Logged out Training TP', 'Others'], hrs: [737466, 169213, 154801, 106000, 96376, 87163, 63238, 62360, 53910, 45040, 43589, 483883], pct: [35.8, 44.1, 51.6, 56.7, 61.4, 65.6, 68.7, 71.7, 74.4, 76.6, 78.7, 100]},
  imp_col: { lbl: ['Implementados', 'En Progreso'], val: [97.94, 2.06]},
  imp_per: { lbl: ['Implementados', 'En Progreso'], val: [97.56, 2.44]},
  imp_det: { cta: ['Ebay', '0'], pais: ['Colombia', '0'], vp: ['Hector Moraira', '0'], mot: ['Restricción de la URL de On Time en la imagen del cliente. no se permite el acceso a herramientas de logueo para el control de tiempos.', '0'], resp: ['Operaciones / Cliente', '0'], fch: ['Sin Definir', '0'], est: ['Pendiente', '0'], obs: ['El staff cuenta con acceso a On Time. pero no hay una herramienta que permita el registro de tiempos. en espera de exposición a Internet de TimeKepper.', '0']},
  ges_mes: { mes: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo'], val: [95.36, 96.57, 96.1, 96.25, 95.92]},
  ges_q: { q: ['Q1', 'Q2'], val: [96.01, 96.09]},
  inc_area: { area: ['Help Desk', 'Master Lilos', 'GBS'], casos: [773, 79, 17], afec: [862257, 60667, 86]},
  inc_mes: { mes: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo'], casos: [183, 61, 87, 145, 273]},
  err_col: { mes: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo'], err: [290, 2316, 355, 421, 300], pct: [0.38, 3.15, 0.47, 0.56, 0.4]},
  err_per: { mes: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo'], err: [56, 122, 176, 44, 30], pct: [0.73, 1.66, 2.47, 0.62, 0.4]},
  extras: { mes: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo'], hrs: [339.18, 264.46, 355.54, 544.94, 683.88], casos: [263, 269, 350, 323, 434]}
};
